const state = {
  isLogged: false,
  currentUser: {
    name: '',
    email: '',
    id: '',
    feedbacks: {
      hasFeedback: false,
      feedbacks: [],
    },

    levels: {
      mapOne: {
        completed: false,
        focusTime: '',
        wrongMoves: '',
        durationToComplete: '',
        hints: '',
      },
      mapTwo: {
        completed: false,
        focusTime: '',
        wrongMoves: '',
        durationToComplete: '',
        hints: '',
      },
      mapThree: {
        completed: false,
        focusTime: '',
        wrongMoves: '',
        durationToComplete: '',
        hints: '',
      },
      mapFour: {
        completed: false,
        focusTime: '',
        wrongMoves: '',
        durationToComplete: '',
        hints: '',
      },
      mapFive: {
        completed: false,
        focusTime: '',
        wrongMoves: '',
        durationToComplete: '',
        hints: '',
      },
      mapSix: {
        completed: false,
        focusTime: '',
        wrongMoves: '',
        durationToComplete: '',
        hints: '',
      },
      mapSeven: {
        completed: false,
        focusTime: '',
        wrongMoves: '',
        durationToComplete: '',
        hints: '',
      },
      mapEight: {
        completed: false,
        focusTime: '',
        wrongMoves: '',
        durationToComplete: '',
        hints: '',
      },
    },
    toWin: {
      mapOne: false,
      mapTwo: false,
      mapThree: false,
      mapFour: false,
      mapFive: false,
      mapSix: false,
      mapSeven: false,
      mapEight: false,
    },
    alreadyEnded: false,
    alreadyBegin: false,
  },
  currentHash: '',
  stopperTimer: '',
};
